import type {
  ContentDetail,
  ContentSummary,
  HomePayload,
  ReactionVideo,
} from "@awesomekorea/shared";

export const previewHomeData: HomePayload = {
  hero: {
    contentSlug: "extreme-job",
    titleKo: "극한직업",
    categoryNameKo: "영화",
    reactionCount: 47,
    message: "오늘 가장 많이 본 반응 콘텐츠",
  },
  top10: [
    {
      rank: 1,
      contentSlug: "extreme-job",
      titleKo: "극한직업",
      categorySlug: "movie",
      categoryNameKo: "영화",
      reactionCount: 47,
      totalViews: 2100000,
      thumbnailUrl: null,
    },
    {
      rank: 2,
      contentSlug: "new-journey-to-the-west",
      titleKo: "신서유기",
      categorySlug: "drama",
      categoryNameKo: "드라마",
      reactionCount: 33,
      totalViews: 1800000,
      thumbnailUrl: null,
    },
    {
      rank: 3,
      contentSlug: "apt",
      titleKo: "APT.",
      categorySlug: "music",
      categoryNameKo: "노래",
      reactionCount: 91,
      totalViews: 5400000,
      thumbnailUrl: null,
    },
    {
      rank: 4,
      contentSlug: "solo-leveling",
      titleKo: "나 혼자만 레벨업",
      categorySlug: "webtoon",
      categoryNameKo: "만화",
      reactionCount: 28,
      totalViews: 1600000,
      thumbnailUrl: null,
    },
    {
      rank: 5,
      contentSlug: "parasite",
      titleKo: "기생충",
      categorySlug: "movie",
      categoryNameKo: "영화",
      reactionCount: 62,
      totalViews: 3200000,
      thumbnailUrl: null,
    },
    {
      rank: 6,
      contentSlug: "queen-of-tears",
      titleKo: "눈물의 여왕",
      categorySlug: "drama",
      categoryNameKo: "드라마",
      reactionCount: 55,
      totalViews: 2500000,
      thumbnailUrl: null,
    },
    {
      rank: 7,
      contentSlug: "squid-game-2",
      titleKo: "오징어게임 S2",
      categorySlug: "drama",
      categoryNameKo: "드라마",
      reactionCount: 110,
      totalViews: 6100000,
      thumbnailUrl: null,
    },
    {
      rank: 8,
      contentSlug: "marvel-webtoon",
      titleKo: "마블 코믹스",
      categorySlug: "webtoon",
      categoryNameKo: "만화",
      reactionCount: 19,
      totalViews: 980000,
      thumbnailUrl: null,
    },
    {
      rank: 9,
      contentSlug: "bokmyeon-song",
      titleKo: "복면가왕 레전드 무대",
      categorySlug: "music",
      categoryNameKo: "노래",
      reactionCount: 22,
      totalViews: 1200000,
      thumbnailUrl: null,
    },
    {
      rank: 10,
      contentSlug: "guardian",
      titleKo: "도깨비",
      categorySlug: "drama",
      categoryNameKo: "드라마",
      reactionCount: 38,
      totalViews: 2900000,
      thumbnailUrl: null,
    },
  ],
  popularByCategory: [
    {
      categorySlug: "all",
      categoryNameKo: "전체",
      items: [],
    },
    {
      categorySlug: "movie",
      categoryNameKo: "영화",
      items: [
        {
          id: 1,
          slug: "extreme-job",
          titleKo: "극한직업",
          titleEn: "Extreme Job",
          categorySlug: "movie",
          categoryNameKo: "영화",
          releaseYear: 2019,
          thumbnailUrl: null,
          description: "해외 유튜브에서 반응이 빠르게 늘고 있는 코미디 영화",
          reactionCount: 47,
          totalViews: 2100000,
          latestReactionAt: "2026-05-30T00:00:00.000Z",
        },
        {
          id: 2,
          slug: "parasite",
          titleKo: "기생충",
          titleEn: "Parasite",
          categorySlug: "movie",
          categoryNameKo: "영화",
          releaseYear: 2019,
          thumbnailUrl: null,
          description: "분석형 리뷰와 첫 감상 영상이 꾸준히 쌓이는 작품",
          reactionCount: 62,
          totalViews: 3200000,
          latestReactionAt: "2026-05-29T18:30:00.000Z",
        },
      ],
    },
    {
      categorySlug: "drama",
      categoryNameKo: "드라마",
      items: [
        {
          id: 3,
          slug: "new-journey-to-the-west",
          titleKo: "신서유기",
          titleEn: "New Journey to the West",
          categorySlug: "drama",
          categoryNameKo: "드라마",
          releaseYear: 2015,
          thumbnailUrl: null,
          description: "예능성 포인트를 좋아하는 해외 채널 반응이 빠른 콘텐츠",
          reactionCount: 33,
          totalViews: 1800000,
          latestReactionAt: "2026-05-30T02:00:00.000Z",
        },
        {
          id: 4,
          slug: "squid-game-2",
          titleKo: "오징어게임 S2",
          titleEn: "Squid Game Season 2",
          categorySlug: "drama",
          categoryNameKo: "드라마",
          releaseYear: 2026,
          thumbnailUrl: null,
          description: "최신순과 인기순 모두 강한 글로벌 반응 콘텐츠",
          reactionCount: 110,
          totalViews: 6100000,
          latestReactionAt: "2026-05-30T04:10:00.000Z",
        },
      ],
    },
    {
      categorySlug: "webtoon",
      categoryNameKo: "만화",
      items: [
        {
          id: 5,
          slug: "solo-leveling",
          titleKo: "나 혼자만 레벨업",
          titleEn: "Solo Leveling",
          categorySlug: "webtoon",
          categoryNameKo: "만화",
          releaseYear: 2018,
          thumbnailUrl: null,
          description: "애니화 이후 해외 리액션 수집 가치가 높은 대표 IP",
          reactionCount: 28,
          totalViews: 1600000,
          latestReactionAt: "2026-05-29T23:45:00.000Z",
        },
        {
          id: 6,
          slug: "marvel-webtoon",
          titleKo: "마블 코믹스",
          titleEn: "Marvel Comics in Korean Translation",
          categorySlug: "webtoon",
          categoryNameKo: "만화",
          releaseYear: 2024,
          thumbnailUrl: null,
          description: "콘텐츠 분류 구조 테스트용 시드 데이터",
          reactionCount: 19,
          totalViews: 980000,
          latestReactionAt: "2026-05-29T14:10:00.000Z",
        },
      ],
    },
    {
      categorySlug: "music",
      categoryNameKo: "노래",
      items: [
        {
          id: 7,
          slug: "apt",
          titleKo: "APT.",
          titleEn: "APT.",
          categorySlug: "music",
          categoryNameKo: "노래",
          releaseYear: 2024,
          thumbnailUrl: null,
          description: "뮤직비디오와 라이브 클립 기반 리액션이 많은 대표 트랙",
          reactionCount: 91,
          totalViews: 5400000,
          latestReactionAt: "2026-05-30T05:00:00.000Z",
        },
        {
          id: 8,
          slug: "bokmyeon-song",
          titleKo: "복면가왕 레전드 무대",
          titleEn: "King of Mask Singer Highlights",
          categorySlug: "music",
          categoryNameKo: "노래",
          releaseYear: 2025,
          thumbnailUrl: null,
          description: "예능형 음악 반응을 담기 위한 시드 카드",
          reactionCount: 22,
          totalViews: 1200000,
          latestReactionAt: "2026-05-29T12:00:00.000Z",
        },
      ],
    },
  ],
  updatedAt: "2026-05-30T08:00:00.000Z",
};

export const previewContentDetail: ContentDetail = {
  id: 1,
  slug: "extreme-job",
  titleKo: "극한직업",
  titleEn: "Extreme Job",
  categorySlug: "movie",
  categoryNameKo: "영화",
  releaseYear: 2019,
  thumbnailUrl: null,
  description: "리액션 영상이 가장 빠르게 붙는 한국 영화 샘플 데이터",
  reactionCount: 47,
  totalViews: 2100000,
  latestReactionAt: "2026-05-30T00:00:00.000Z",
  aliases: ["Extreme Job", "극한직업 reaction", "Korean comedy movie"],
};

export const previewReactions: ReactionVideo[] = [
  {
    id: 1,
    youtubeVideoId: "react-001",
    title: "극한직업 보고 충격받은 미국인 반응",
    thumbnailUrl: null,
    publishedAt: "2026-05-30T00:00:00.000Z",
    viewCount: 312000,
    likeCount: 21000,
    commentCount: 1400,
    youtubeUrl: "https://www.youtube.com/watch?v=react-001",
    channelName: "ReactKing",
  },
  {
    id: 2,
    youtubeVideoId: "react-002",
    title: "Americans watch Extreme Job for the first time",
    thumbnailUrl: null,
    publishedAt: "2026-05-29T20:00:00.000Z",
    viewCount: 208000,
    likeCount: 15600,
    commentCount: 970,
    youtubeUrl: "https://www.youtube.com/watch?v=react-002",
    channelName: "FilmReact",
  },
  {
    id: 3,
    youtubeVideoId: "react-003",
    title: "이 영화 진짜임? | 극한직업 리액션",
    thumbnailUrl: null,
    publishedAt: "2026-05-29T12:30:00.000Z",
    viewCount: 177000,
    likeCount: 12000,
    commentCount: 830,
    youtubeUrl: "https://www.youtube.com/watch?v=react-003",
    channelName: "WatchKorea",
  },
];

export const flattenPopularCards = (sections: HomePayload["popularByCategory"]): ContentSummary[] =>
  sections.flatMap((section) => section.items);
